### ISSUE TITLE
Not run with kotlin version 1.2.21

### ISSUE THREAD

**Issue by hectorlicea** [dustinsand/lagom-helloworld-java-to-kotlin#1]
Hi:
I try to compile and run with Kotlin version 1.2.21 and the example not run. 

Thank you for your attention, HLicea

**Comment by dustinsand** [comment]
Hi Hector,

Updated project to Kotlin 1.2.30 and Lagom 1.4.1.  I'm not seeing any compilation, test or runtime issues.

Can you provide more details about the issue you are having?

Dustin

**Comment by hectorlicea** [comment]
I'm sorry. I had a corrupt dependencies. I recompiled again and all ok. 
Thank you very much for your attention.
HLicea
